### ISSUE TITLE
设置的prefix为“fat-es5:”，remove_prefix为默认值，查询语句为GET fat-es5:article_search/_search，结果提示rticle_search索引不存在，为啥把article_search截断为rticle_search？

### ISSUE THREAD

**Issue by dengdalue** [infinilabs/gateway#20]
设置的prefix为“fat-es5:”，remove_prefix为默认值，查询语句为GET fat-es5:article_search/_search，结果提示rticle_search索引不存在，为啥把article_search截断为rticle_search？

**Comment by medcl** [comment]
确实好像有 bug，去掉 - 是可以的，正在解决中。

**Comment by medcl** [comment]
已解决，golang 的一个坑，请下载最新的 670 版本。
