### ISSUE TITLE
极限网关开启后，使用不了

### ISSUE THREAD

**Issue by GuaKin-Huang** [infinilabs/gateway#27]
![image](https://user-images.githubusercontent.com/24251728/185526622-70897258-c1cd-44f8-aa3e-df03b72a8e65.png)
请求8000端口后，返回401
![image](https://user-images.githubusercontent.com/24251728/185526731-6d15881e-628a-49bd-965c-61593163fc62.png)

**Comment by GuaKin-Huang** [comment]
请问下，哪里出问题，都是按官网教程弄的

**Comment by medcl** [comment]
网关是透明转发，访问网关还是需要继续传实际的身份信息的啊-------- 原始邮件 --------发件人： GuaKin_Huang ***@***.***>日期： 2022年8月19日周五 上午10:05收件人： infinilabs/gateway ***@***.***>抄送： Subscribed ***@***.***>主    题： [infinilabs/gateway] 极限网关开启后，使用不了 (Issue #27)



请求8000端口后，返回401
