### ISSUE TITLE
Elasticsearch 配置里面provider ，region ，dc的含义和使用场景

### ISSUE THREAD

**Issue by huangsanye** [infinilabs/gateway#33]
Elasticsearch 配置里面provider ，region ，dc的含义和使用场景，我们可能存在一个es 集群在不同阿里云的分区。

**Comment by huangsanye** [comment]
所以希望网关能根据自己的分区，优先访问这个分区的es 结点

**Comment by medcl** [comment]
https://www.infinilabs.com/docs/latest/gateway/references/filters/elasticsearch/#%e8%bf%87%e6%bb%a4%e8%8a%82%e7%82%b9
你用自定义标签就可以实现按需过滤节点，看看是不是你要的这个功能

**Comment by huangsanye** [comment]
您好，这个过滤不是我们想要的，我们还是要的是优先同区访问

**Comment by huangsanye** [comment]
比如我们有两个gateway，分别在阿里云的g区，和h区，我们希望部署在g区的gateway优先访问g区的es 结点，我看provider ，region ，dc这些配置是否能实现

**Comment by medcl** [comment]
优先同区访问的案例可以看这个：
https://www.infinilabs.com/docs/latest/gateway/user-cases/stories/a_cross_region_cluster_access_locality/

目前provider ，region ，dc 只是用来描述这些资源的。

**Comment by huangsanye** [comment]
- set_request_query_args:
        args:
          - preference -> _prefer_nodes:node-id-of-data-baidu01,node-id-of-data-baidu02 #通过配置preference的_prefer_nodes为所有的百度data节点的node_id，来实现百度云的业务优先访问百度云的节点，最大程度避免跨云访问，对业务更友好。
 


 您好 您这里的prefer_node 信息，是业务查询的时候args 里面带的吗？
