### ISSUE TITLE
启动时报无法分配内存

### ISSUE THREAD

**Issue by liuying525** [infinilabs/gateway#35]
### Description

想要通过gateway想要实现ES两个集群间的数据同步。操作系统版本为redhat linux 7.3，安装的INFINI GATEWAY 版本是[gateway-1.12.0-915-linux-386.tar.gz](https://release.infinilabs.com/gateway/stable/gateway-1.12.0-915-linux-386.tar.gz)。两个集群IP地址分别为10.0.121.16和10.0.121.47，将gateway安装在10.0.121.47的机器上。启动gateway报错截图如下：
![报错信息](https://user-images.githubusercontent.com/48663450/232643191-e0721a6b-f93d-489b-b739-1d5f99549b92.PNG)

配置的yml如下：
path.data: data
path.logs: log

elasticsearch:
- name: es-cluster1
  enabled: true
  endpoint: http://10.0.121.47:9200

- name: ecs
  enabled: true
  endpoint: http://10.0.121.16:9201
  basic_auth:
    username: elastic
    password: puBlSwHy+hmk-7IREynR

entry:
  - name: my_es_entry
    enabled: true
    router: my_router
    network:
      binding: 0.0.0.0:8000

flow:
  - name: write-flow
    filter:
      - if:
          cluster_available: ["es-cluster1"]
        then:
          - elasticsearch:
              elasticsearch: "es-cluster1"
          - queue:
              queue_name: "ecs-queue"
        else:
          - elasticsearch:
              elasticsearch: "ecs"
          - queue:
              queue_name: "es-cluster1-queue"
  - name: read-flow
    filter:
      - if:
          cluster_available: ["es-cluster1"]
        then:
          - elasticsearch:
              elasticsearch: "es-cluster1"
        else:
          - elasticsearch:
              elasticsearch: "ecs"

router:
  - name: my_router
    default_flow: write-flow
    rules:
      - method:
          - "GET"
          - "HEAD"
        pattern:
          - "/{any:*}"
        flow:
          - read-flow
      - method:
          - "POST"
          - "GET"
        pattern:
          - "/_refresh"
          - "/_count"
          - "/_search"
          - "/_msearch"
          - "/_mget"
          - "/{any_index}/_count"
          - "/{any_index}/_search"
          - "/{any_index}/_msearch"
          - "/{any_index}/_mget"
        flow:
          - read-flow

pipeline:
  - name: es-cluster1-consumer
    auto_start: true
    keep_running: true
    processor:
      - queue_consumer:
          input_queue: "es-cluster1-queue" 
          elasticsearch: "es-cluster1"
          when:
            cluster_available: ["es-cluster1"] 
  - name: ecs-consumer
    auto_start: true
    keep_running: true
    processor:
      - queue_consumer:
          input_queue: "ecs-queue"
          elasticsearch: "ecs"
          when:
            cluster_available: ["ecs"]

### Environment

操作系统版本为redhat linux 7.3

**Comment by medcl** [comment]
内存给了多少呢？并发多少？

**Comment by medcl** [comment]
双写的配置可以直接用这个：https://github.com/infinilabs/testing/blob/main/setup/gateway/cases/replication/replication_nonstop-search.yml

**Comment by liuying525** [comment]
> 内存给了多少呢？并发多少？
服务器内存：64G，安装的ES设置的Xms和Xmx内存均为512m。
由于是实验环境，没有数据实时写入，不存在高并发的情况

**Comment by medcl** [comment]
下载的包不对，下载 amd64 的包，386 是 32 位用的
