### ISSUE TITLE
kibnana的dashboard导入提示错误

### ISSUE THREAD

**Issue by duyingsoft** [infinilabs/gateway#36]
是按https://www.infinilabs.com/docs/latest/gateway/tutorial/request-logging/这边的提供的dashboard导入，这边是说kibana7.9
![image](https://github.com/infinilabs/gateway/assets/13470619/8f3e159a-eadd-48fa-b857-219c815e48b9)
我的也是是7.9.3，但是提示导入失败
![image](https://github.com/infinilabs/gateway/assets/13470619/604166c5-ce85-4ba2-8226-b8396c177447)

看接口返回好像是kibana兼容性问题
`{
    "statusCode": 422,
    "error": "Unprocessable Entity",
    "message": "Document \"b1af6220-0f7a-11eb-8973-2f461ac7af4d\" has property \"visualization\" which belongs to a more recent version of Kibana [7.10.0]. The last known version is [7.9.3]"
}`

看提示，是要求要7.10版本的，请问是否文档写的有问题

**Comment by medcl** [comment]
你试试另外的几个 dashboard 呢？
如果实在导入不进去，手动配置一下也很快的。
Kibana 太重了，我们现在倾向于在 Console 里面去做分析，更加轻量级。
<img width="1469" alt="image" src="https://github.com/infinilabs/gateway/assets/64487/33529c95-b92d-4691-872e-6510f71e5be5">

**Comment by duyingsoft** [comment]
好的。我用console试一下
