### ISSUE TITLE
生产环境产生大量的监控数据，导致kafka硬盘写满

### ISSUE THREAD

**Issue by lygsniper** [infinilabs/gateway#42]
### 问题描述

我们在生产环境使用极限网关同步ES数据到灾备环境，过了一段时间，发现kafka宕机了，查找问题是因为kafka硬盘被写满了，看kafka数据全是极限网关发送的监控数据，有10G左右，最后分析kafka数据，差不多每天产生1.3-1.5G的监控数据，但是开发环境并没有这么大的数据量。
通过分析kafka数据，发现生产环境10s产生18条监控数据，而开发环境只产生2条，这个就是为什么生产数据量大的原因，但是为啥每次会产生18条这么多的数据，这个是我的疑问？请各位大佬分析分析

**Comment by medcl** [comment]
详细的配置和数据样本可以提供一下么？

**Comment by lygsniper** [comment]
![1](https://github.com/infinilabs/gateway/assets/9794571/d1c8f70c-8c17-4548-bfc7-5ef06355cb62)
![2](https://github.com/infinilabs/gateway/assets/9794571/59f95473-997d-4a56-a88b-c14ab64978a5)
![3](https://github.com/infinilabs/gateway/assets/9794571/825635e5-7466-478e-bdc3-c7540cd99d25)
![4](https://github.com/infinilabs/gateway/assets/9794571/7c877c67-ab64-4cb6-82e3-61316977282e)
![5](https://github.com/infinilabs/gateway/assets/9794571/66bbc054-4d0d-4a63-8705-a3afa5ffabf6)
![6](https://github.com/infinilabs/gateway/assets/9794571/0dd346dc-bf00-4483-bb62-0287f90b0981)
![7](https://github.com/infinilabs/gateway/assets/9794571/8d1ffef0-10d9-47f0-ba74-bfe500261945)
![8](https://github.com/infinilabs/gateway/assets/9794571/7b445ecd-0fb6-4d71-8273-abcbf5456f46)
![9](https://github.com/infinilabs/gateway/assets/9794571/f8b0dd33-ecbf-412b-9f24-2682b1f724e0)
![10](https://github.com/infinilabs/gateway/assets/9794571/a66d8f02-d00d-4794-8b6d-6e40cdcdf279)
![11](https://github.com/infinilabs/gateway/assets/9794571/b0a95414-6cd4-42d6-b4b6-94c605881b2d)
![12](https://github.com/infinilabs/gateway/assets/9794571/7250d1e0-1941-4ff9-a1a3-cf61d811accc)
![13](https://github.com/infinilabs/gateway/assets/9794571/ef54534b-4590-4354-8560-01ab270b3a03)
![14](https://github.com/infinilabs/gateway/assets/9794571/e5d59603-d15e-4a3a-9a20-8e03430f6286)
![15](https://github.com/infinilabs/gateway/assets/9794571/e7d83ef1-37ab-46d2-b820-c2792392d12e)
![16](https://github.com/infinilabs/gateway/assets/9794571/5611a6b9-347a-4f2b-8d9b-c00e8b9c6422)
![17](https://github.com/infinilabs/gateway/assets/9794571/180aa001-5776-4c39-ab4f-8cc5045da685)
![18](https://github.com/infinilabs/gateway/assets/9794571/a57b659f-b708-4b90-bb2f-15c5f7054735)
![19](https://github.com/infinilabs/gateway/assets/9794571/2a1a8e0b-9da2-4979-8f7d-552573d65058)
![20](https://github.com/infinilabs/gateway/assets/9794571/b29b40c7-c716-4da0-ae23-95accccddbd9)
![21](https://github.com/infinilabs/gateway/assets/9794571/f8496a8c-7bba-4178-98bd-c3a2433d5e01)
![22](https://github.com/infinilabs/gateway/assets/9794571/c359c996-8f60-4b9c-8585-fc00b5bf0f41)
![23](https://github.com/infinilabs/gateway/assets/9794571/95e4a9eb-5400-48d1-8b3e-e5ba8492d35a)
![222](https://github.com/infinilabs/gateway/assets/9794571/1f34f828-4d63-4ce1-a8b9-89c627a634f1)

**Comment by medcl** [comment]
这些采集的数据是网关实例上报的指标数据，如果需要可以通过参数 `METRIC_ENABLED: false` 来进行关闭。
关于两个环境的差钱，具体数据你可以进行分析一下，每一条都有唯一的类型标识，不同的网卡也会分布采集上报。
