### ISSUE TITLE
通过极限网关存储数据，提示larger than the max message size the server will accept.

### ISSUE THREAD

**Issue by lygsniper** [infinilabs/gateway#45]
大家好，遇到一个问题：通过极限网关保存ES数据的时候，提示：the request included a message larger than the max message size the server will accept.   修改极限网关配置文件：
processor:
  - consumer:
       ...
       queue_selector:
         labels:
             type: "primary_write_ahead_log"
       consumer:
         fetch_max_messages:  **10000000**    #修改此处为1000万，保存重启网关，仍然报上面错误

who can help me?

**Comment by medcl** [comment]
10000000 也太大了吧，这个是单个批次的消息大小，不是累计的

**Comment by medcl** [comment]
10000000 也太大了吧，这个是单个批次的消息大小，不是累计的
