### ISSUE TITLE
gateway在本地无法make

### ISSUE THREAD

**Issue by happyrita** [infinilabs/gateway#6]
### Description

大大好，gateway在本地无法运行，拉取依赖时发现 https://github.com/medcl/infini-framework.git 不存在。

### Steps to reproduce

1. Start INFINI Gateway
2. Second step
3. Third step

### Expected behavior

A description of what you expected to happen.

### Actual behavior

A description of what happens instead.

### Environment

* Build: [e.g. gateway 1.0.0_SNAPSHOT 2021-09-05 15:41:02 1a8f196 - type "-v" in the Command Palette]
* Operating system and version: [e.g. macOS 10.14, Windows 10, Ubuntu 18.04]
* [Linux] Desktop Environment and/or Window Manager: [e.g. Gnome, LXDE, i3]

**Comment by medcl** [comment]
封闭开发中，近期没有开源计划，敬请关注。
